import 'package:geolocator/geolocator.dart';

class AssistDirectory {
  AssistDirectory._();

  static List<Map<String, dynamic>> sortedProviders(
    List<Map<String, dynamic>> providers, {
    required double latitude,
    required double longitude,
  }) {
    final sorted = List<Map<String, dynamic>>.from(providers);
    sorted.sort((left, right) {
      final leftDistance = Geolocator.distanceBetween(
        latitude,
        longitude,
        (left['lat'] as num).toDouble(),
        (left['lng'] as num).toDouble(),
      );
      final rightDistance = Geolocator.distanceBetween(
        latitude,
        longitude,
        (right['lat'] as num).toDouble(),
        (right['lng'] as num).toDouble(),
      );
      return leftDistance.compareTo(rightDistance);
    });
    return sorted;
  }

  static Map<String, dynamic>? nearestProvider(
    List<Map<String, dynamic>> providers, {
    required double latitude,
    required double longitude,
  }) {
    final sorted = sortedProviders(
      providers,
      latitude: latitude,
      longitude: longitude,
    );
    if (sorted.isEmpty) {
      return null;
    }
    return sorted.first;
  }

  static const List<Map<String, dynamic>> healthProviders = [
    {
      'id': 'hospital_shah_alam',
      'name': 'Hospital Shah Alam',
      'short': 'HSA',
      'address': 'Persiaran Kayangan, Shah Alam',
      'phone': '+60355263000',
      'availability': '24/7 trauma response',
      'lat': 3.0827,
      'lng': 101.5320,
    },
    {
      'id': 'sunway_medical',
      'name': 'Sunway Medical Centre',
      'short': 'SMC',
      'address': 'Bandar Sunway, Petaling Jaya',
      'phone': '+60374919191',
      'availability': 'Emergency bay open',
      'lat': 3.0705,
      'lng': 101.6071,
    },
    {
      'id': 'kl_general',
      'name': 'Hospital Kuala Lumpur',
      'short': 'HKL',
      'address': 'Jalan Pahang, Kuala Lumpur',
      'phone': '+60326155555',
      'availability': 'Critical care available',
      'lat': 3.1722,
      'lng': 101.6997,
    },
    {
      'id': 'putrajaya_hospital',
      'name': 'Hospital Putrajaya',
      'short': 'HPJ',
      'address': 'Presint 7, Putrajaya',
      'phone': '+60383124200',
      'availability': 'Emergency support',
      'lat': 2.9317,
      'lng': 101.6893,
    },
    {
      'id': 'serdang_hospital',
      'name': 'Hospital Serdang',
      'short': 'HSD',
      'address': 'Jalan Puchong, Serdang',
      'phone': '+60389475555',
      'availability': 'Red zone active',
      'lat': 2.9732,
      'lng': 101.7188,
    },
    {
      'id': 'sjmc',
      'name': 'Subang Jaya Medical Centre',
      'short': 'SJMC',
      'address': 'Subang Jaya, Selangor',
      'phone': '+60356391212',
      'availability': 'Emergency physicians ready',
      'lat': 3.0778,
      'lng': 101.5913,
    },
    {
      'id': 'columbia_asia_pj',
      'name': 'Columbia Asia Petaling Jaya',
      'short': 'CAPJ',
      'address': 'Seksyen 13, Petaling Jaya',
      'phone': '+60379469999',
      'availability': 'Ambulance entry open',
      'lat': 3.1128,
      'lng': 101.6386,
    },
    {
      'id': 'assunta',
      'name': 'Assunta Hospital',
      'short': 'ASH',
      'address': 'Jalan Templer, Petaling Jaya',
      'phone': '+60378723000',
      'availability': 'Emergency room available',
      'lat': 3.1036,
      'lng': 101.6421,
    },
    {
      'id': 'ummc',
      'name': 'University Malaya Medical Centre',
      'short': 'UMMC',
      'address': 'Lembah Pantai, Kuala Lumpur',
      'phone': '+60379494422',
      'availability': 'Trauma support ready',
      'lat': 3.1126,
      'lng': 101.6529,
    },
    {
      'id': 'ukm_hospital',
      'name': 'Hospital Canselor Tuanku Muhriz',
      'short': 'HCTM',
      'address': 'Cheras, Kuala Lumpur',
      'phone': '+60391455555',
      'availability': 'Emergency team active',
      'lat': 3.0958,
      'lng': 101.7258,
    },
    {
      'id': 'ampang_hospital',
      'name': 'Hospital Ampang',
      'short': 'HAG',
      'address': 'Jalan Mewah Utara, Ampang',
      'phone': '+60342896000',
      'availability': 'Casualty unit open',
      'lat': 3.1545,
      'lng': 101.7617,
    },
    {
      'id': 'selayang_hospital',
      'name': 'Hospital Selayang',
      'short': 'HSL',
      'address': 'Lebuhraya Selayang-Kepong',
      'phone': '+60361203233',
      'availability': 'Emergency specialists on call',
      'lat': 3.2416,
      'lng': 101.6742,
    },
    {
      'id': 'sime_darby_ara',
      'name': 'Ara Damansara Medical Centre',
      'short': 'ADMC',
      'address': 'Ara Damansara, Petaling Jaya',
      'phone': '+60356391212',
      'availability': 'Urgent care available',
      'lat': 3.1103,
      'lng': 101.5724,
    },
    {
      'id': 'pantai_hospital',
      'name': 'Pantai Hospital Kuala Lumpur',
      'short': 'PHKL',
      'address': 'Jalan Bukit Pantai, Kuala Lumpur',
      'phone': '+60322960888',
      'availability': 'Emergency desk open',
      'lat': 3.0968,
      'lng': 101.6672,
    },
    {
      'id': 'gleneagles_kl',
      'name': 'Gleneagles Kuala Lumpur',
      'short': 'GKL',
      'address': 'Jalan Ampang, Kuala Lumpur',
      'phone': '+60341413000',
      'availability': 'Critical care standby',
      'lat': 3.1646,
      'lng': 101.7324,
    },
    {
      'id': 'kpj_damansara',
      'name': 'KPJ Damansara Specialist',
      'short': 'KPJ',
      'address': 'Damansara Utama, Petaling Jaya',
      'phone': '+60377226900',
      'availability': 'Emergency specialists ready',
      'lat': 3.1312,
      'lng': 101.6231,
    },
    {
      'id': 'thomson_hospital',
      'name': 'Thomson Hospital Kota Damansara',
      'short': 'THM',
      'address': 'Kota Damansara, Selangor',
      'phone': '+60362871212',
      'availability': 'Rapid triage available',
      'lat': 3.1553,
      'lng': 101.5942,
    },
    {
      'id': 'cyberjaya_clinic',
      'name': 'Cyberjaya Emergency Clinic',
      'short': 'CEC',
      'address': 'Lingkaran Cyber Point, Cyberjaya',
      'phone': '+60383254400',
      'availability': 'Walk-in emergency support',
      'lat': 2.9206,
      'lng': 101.6569,
    },
  ];

  static const List<Map<String, dynamic>> technicianProviders = [
    {
      'id': 'evsmart_mobile',
      'name': 'EVSmart Mobile Technician',
      'short': 'ES+',
      'address': 'Petaling Jaya service radius',
      'phone': '+60377881111',
      'availability': 'Can arrive in 18 min',
      'lat': 3.1372,
      'lng': 101.6237,
    },
    {
      'id': 'selangor_ev_care',
      'name': 'Selangor EV Care',
      'short': 'SEC',
      'address': 'Subang Jaya service center',
      'phone': '+60356372222',
      'availability': 'Battery and towing support',
      'lat': 3.0796,
      'lng': 101.5868,
    },
    {
      'id': 'kl_battery_rescue',
      'name': 'KL Battery Rescue',
      'short': 'KBR',
      'address': 'Jalan Tun Razak, Kuala Lumpur',
      'phone': '+60340228888',
      'availability': 'High-voltage inspection ready',
      'lat': 3.1597,
      'lng': 101.7174,
    },
    {
      'id': 'cyber_ev_specialist',
      'name': 'Cyber EV Specialist',
      'short': 'CES',
      'address': 'Cyberjaya roadside team',
      'phone': '+60383254444',
      'availability': 'Remote diagnostics + on-site',
      'lat': 2.9206,
      'lng': 101.6569,
    },
    {
      'id': 'pj_ev_recovery',
      'name': 'PJ EV Recovery',
      'short': 'PJR',
      'address': 'Section 13, Petaling Jaya',
      'phone': '+60379561234',
      'availability': 'Tow truck on standby',
      'lat': 3.1117,
      'lng': 101.6349,
    },
    {
      'id': 'ampang_ev_support',
      'name': 'Ampang EV Support',
      'short': 'AES',
      'address': 'Jalan Ampang, Kuala Lumpur',
      'phone': '+60342665555',
      'availability': 'Roadside dispatch ready',
      'lat': 3.1549,
      'lng': 101.7448,
    },
    {
      'id': 'gombak_ev_rescue',
      'name': 'Gombak EV Rescue',
      'short': 'GER',
      'address': 'Batu Caves, Selangor',
      'phone': '+60361881234',
      'availability': 'Recovery team available',
      'lat': 3.2373,
      'lng': 101.6840,
    },
    {
      'id': 'cheras_ev_lab',
      'name': 'Cheras EV Lab',
      'short': 'CEL',
      'address': 'Cheras service corridor',
      'phone': '+60391314444',
      'availability': 'Battery diagnostics open',
      'lat': 3.0886,
      'lng': 101.7434,
    },
    {
      'id': 'klang_ev_responder',
      'name': 'Klang EV Responder',
      'short': 'KER',
      'address': 'Bukit Tinggi, Klang',
      'phone': '+60333457777',
      'availability': 'Bodywork and towing support',
      'lat': 3.0202,
      'lng': 101.4458,
    },
    {
      'id': 'putrajaya_ev_assist',
      'name': 'Putrajaya EV Assist',
      'short': 'PEA',
      'address': 'Presint 15, Putrajaya',
      'phone': '+60388811234',
      'availability': 'Fast roadside response',
      'lat': 2.9586,
      'lng': 101.7202,
    },
    {
      'id': 'shah_alam_ev_team',
      'name': 'Shah Alam EV Team',
      'short': 'SAE',
      'address': 'Seksyen 15, Shah Alam',
      'phone': '+60355118822',
      'availability': 'Charging and powertrain checks',
      'lat': 3.0721,
      'lng': 101.5189,
    },
    {
      'id': 'damansara_ev_pro',
      'name': 'Damansara EV Pro',
      'short': 'DEP',
      'address': 'Mutiara Damansara, Petaling Jaya',
      'phone': '+60377229911',
      'availability': 'Diagnostic van ready',
      'lat': 3.1598,
      'lng': 101.6116,
    },
    {
      'id': 'subang_ev_oncall',
      'name': 'Subang EV On-Call',
      'short': 'SEO',
      'address': 'USJ, Subang Jaya',
      'phone': '+60380235566',
      'availability': 'Mobile tire and brake support',
      'lat': 3.0446,
      'lng': 101.5812,
    },
    {
      'id': 'nilai_ev_support',
      'name': 'Nilai EV Support',
      'short': 'NES',
      'address': 'Nilai service route',
      'phone': '+6067991234',
      'availability': 'Highway coverage available',
      'lat': 2.8167,
      'lng': 101.7969,
    },
    {
      'id': 'kajang_ev_works',
      'name': 'Kajang EV Works',
      'short': 'KEW',
      'address': 'Kajang town service point',
      'phone': '+60387336622',
      'availability': 'Suspension and body checks',
      'lat': 2.9927,
      'lng': 101.7909,
    },
    {
      'id': 'bangi_ev_network',
      'name': 'Bangi EV Network',
      'short': 'BEN',
      'address': 'Bandar Baru Bangi',
      'phone': '+60389263311',
      'availability': 'EV roadside crew',
      'lat': 2.9604,
      'lng': 101.7577,
    },
    {
      'id': 'puchong_ev_response',
      'name': 'Puchong EV Response',
      'short': 'PER',
      'address': 'Bandar Puchong Jaya',
      'phone': '+60380751122',
      'availability': 'Tow and workshop coordination',
      'lat': 3.0327,
      'lng': 101.6188,
    },
    {
      'id': 'rawang_ev_rescue',
      'name': 'Rawang EV Rescue',
      'short': 'RER',
      'address': 'Rawang north route',
      'phone': '+60360913322',
      'availability': 'Long-range recovery support',
      'lat': 3.3210,
      'lng': 101.5767,
    },
    {
      'id': 'kepong_ev_support',
      'name': 'Kepong EV Support',
      'short': 'KES',
      'address': 'Kepong workshop strip',
      'phone': '+60362574422',
      'availability': 'On-call EV mechanic',
      'lat': 3.2143,
      'lng': 101.6359,
    },
    {
      'id': 'setapak_ev_mobile',
      'name': 'Setapak EV Mobile',
      'short': 'SEM',
      'address': 'Setapak roadside coverage',
      'phone': '+60341445522',
      'availability': 'Mobile EV inspection',
      'lat': 3.1889,
      'lng': 101.7232,
    },
    {
      'id': 'wangsa_ev_support',
      'name': 'Wangsa EV Support',
      'short': 'WES',
      'address': 'Wangsa Maju service point',
      'phone': '+60341491133',
      'availability': 'Nearby dispatch available',
      'lat': 3.2050,
      'lng': 101.7375,
    },
    {
      'id': 'mont_kiara_ev_team',
      'name': 'Mont Kiara EV Team',
      'short': 'MKT',
      'address': 'Mont Kiara, Kuala Lumpur',
      'phone': '+60362013355',
      'availability': 'Fast premium EV support',
      'lat': 3.1707,
      'lng': 101.6524,
    },
    {
      'id': 'desa_park_ev_care',
      'name': 'Desa Park EV Care',
      'short': 'DPC',
      'address': 'Desa ParkCity service lane',
      'phone': '+60362634455',
      'availability': 'Roadside diagnostics',
      'lat': 3.1926,
      'lng': 101.6297,
    },
    {
      'id': 'klcc_ev_response',
      'name': 'KLCC EV Response',
      'short': 'KLR',
      'address': 'City Centre mobile team',
      'phone': '+60321667788',
      'availability': 'Central business district coverage',
      'lat': 3.1579,
      'lng': 101.7123,
    },
    {
      'id': 'sentul_ev_assist',
      'name': 'Sentul EV Assist',
      'short': 'SEA',
      'address': 'Sentul transport corridor',
      'phone': '+60340453322',
      'availability': 'Tow truck linked',
      'lat': 3.1858,
      'lng': 101.6945,
    },
    {
      'id': 'batu_caves_ev_team',
      'name': 'Batu Caves EV Team',
      'short': 'BET',
      'address': 'Batu Caves workshop road',
      'phone': '+60361895544',
      'availability': 'Battery and inverter checks',
      'lat': 3.2378,
      'lng': 101.6841,
    },
    {
      'id': 'seri_kembangan_ev_lab',
      'name': 'Seri Kembangan EV Lab',
      'short': 'SKL',
      'address': 'Seri Kembangan support route',
      'phone': '+60389412255',
      'availability': 'Hybrid and EV diagnostics',
      'lat': 3.0300,
      'lng': 101.7053,
    },
    {
      'id': 'balakong_ev_works',
      'name': 'Balakong EV Works',
      'short': 'BEW',
      'address': 'Balakong industrial area',
      'phone': '+60389615522',
      'availability': 'Body repair and battery review',
      'lat': 3.0285,
      'lng': 101.7468,
    },
    {
      'id': 'semenyih_ev_support',
      'name': 'Semenyih EV Support',
      'short': 'SES',
      'address': 'Semenyih route coverage',
      'phone': '+60387245522',
      'availability': 'Roadside recovery ready',
      'lat': 2.9519,
      'lng': 101.8434,
    },
    {
      'id': 'port_klang_ev_rescue',
      'name': 'Port Klang EV Rescue',
      'short': 'PKR',
      'address': 'Port Klang coastal corridor',
      'phone': '+60331687722',
      'availability': 'Heavy recovery crew',
      'lat': 3.0014,
      'lng': 101.3928,
    },
    {
      'id': 'meru_ev_team',
      'name': 'Meru EV Team',
      'short': 'MET',
      'address': 'Meru township service area',
      'phone': '+60333925522',
      'availability': 'Roadside technician on standby',
      'lat': 3.1469,
      'lng': 101.4278,
    },
    {
      'id': 'saujana_putra_ev_support',
      'name': 'Saujana Putra EV Support',
      'short': 'SPS',
      'address': 'Saujana Putra connector road',
      'phone': '+60380665511',
      'availability': 'Fast highway response',
      'lat': 2.9837,
      'lng': 101.5560,
    },
  ];
}
