// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRs1tS9yobBzOtkp-U3mqVfu9swTij1EU',
    appId: '1:1016507832438:web:8a77cfb51c61b922e26757',
    messagingSenderId: '1016507832438',
    projectId: 'evsmart-2694c',
    authDomain: 'evsmart-2694c.firebaseapp.com',
    databaseURL:
        'https://evsmart-2694c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'evsmart-2694c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoCv0-a-2ifdpDo1vXhJ4rV0hqcMN60IA',
    appId: '1:1016507832438:android:66023a26b0427f86e26757',
    messagingSenderId: '1016507832438',
    projectId: 'evsmart-2694c',
    databaseURL:
        'https://evsmart-2694c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'evsmart-2694c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlY1HcGiR9pjkCeL4jgMki4NKKsgv5y_U',
    appId: '1:1016507832438:ios:fc56018a8b2f56dfe26757',
    messagingSenderId: '1016507832438',
    projectId: 'evsmart-2694c',
    databaseURL:
        'https://evsmart-2694c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'evsmart-2694c.firebasestorage.app',
    iosBundleId: 'com.evsmart.plus.evsmartPlus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlY1HcGiR9pjkCeL4jgMki4NKKsgv5y_U',
    appId: '1:1016507832438:ios:fc56018a8b2f56dfe26757',
    messagingSenderId: '1016507832438',
    projectId: 'evsmart-2694c',
    databaseURL:
        'https://evsmart-2694c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'evsmart-2694c.firebasestorage.app',
    iosBundleId: 'com.evsmart.plus.evsmartPlus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRs1tS9yobBzOtkp-U3mqVfu9swTij1EU',
    appId: '1:1016507832438:web:613fedabf0a2226ee26757',
    messagingSenderId: '1016507832438',
    projectId: 'evsmart-2694c',
    authDomain: 'evsmart-2694c.firebaseapp.com',
    databaseURL:
        'https://evsmart-2694c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'evsmart-2694c.firebasestorage.app',
  );
}
